### ISSUE TITLE
Project Review: Summary

### ISSUE THREAD

**Issue by SidTheEngineer** [claytondecker/prj-rev-bwfs-dasmoto#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4/4
* _Comment(s):_ CSS file is appropriately linked to the HTML using a relative path
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4/4
* _Comment(s):_ Everything from the design specification regarding styles/content is included here. 
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4/4
* _Comment(s):_ Overall your HTML looks great! Formatting/indentation is perfect, elements are used appropriately, and `alt` image attributes/descriptions were included.
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4/4
* _Comment(s):_ CSS selectors/syntax look solid as well. The only minor issue I noticed here was a missing semi-colon on line 12. Beyond this, nice work with the CSS/styling of the site.
 
### Overall Score: 16/16 🔥 
Nice work with the project. It's pretty much spot on with the design specification/solution.

**Comment by claytondecker** [comment]
Added the semicolon. Thank for the review!
